apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stagelog-auth-env
  namespace: stagelog
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameterstore
    kind: ClusterSecretStore
  target:
    name: stagelog-auth-env
    creationPolicy: Owner
  data:
  - secretKey: .env
    remoteRef:
      key: /stagelog/dev/auth/.env
